apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: jenkins-agent-maven-36-rhel7
  name: jenkins-agent-maven-36-rhel7
  namespace: nos-automation
spec:
  source:
    git:
      uri: https://github.com/ruhan1/commonjava-images.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: jenkins/openshift3/jenkins-agent-maven-36-rhel7/Dockerfile
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-agent-maven-36-rhel7:latest
